-- Criação do Banco de Dados 
CREATE DATABASE LOJA_INFORMATICA CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE loja_informatica;

-- 1. Tabela CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL
);

-- 2. Tabela FORNECEDOR
CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    CNPJ CHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(150)	NOT NULL,
    TELEFONE CHAR(11) NOT NULL
);

-- 3. Tabela ENDERECO
CREATE TABLE ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    CEP CHAR(8) NOT NULL,
    RUA VARCHAR(150) NOT NULL,
    NUMERO INT NOT NULL
);

-- 4. Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    TELEFONE CHAR(11) NOT NULL,
    E_MAIL VARCHAR(150) NOT NULL,
    CPF_CNPJ CHAR(14) NOT NULL UNIQUE,
    TIPO VARCHAR(14) NOT NULL,
    CONSTRAINT CLIENTE_CHK_TIPO CHECK (TIPO IN ('FÍSICA', 'JURÍDICA')) 
);

-- 5. Tabela PAGAMENTO
CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    CRIACAO DATE NOT NULL,
    VENCIMENTO DATE,
    TIPO VARCHAR(8) NOT NULL ,
    STATUS VARCHAR(9) NOT NULL,
    CONSTRAINT PAGAMENTO_CHK_STATUS CHECK (STATUS IN ('PENDENTE', 'REALIZADO', 'RECUSADO')),
    CONSTRAINT PAGAMENTO_CHK_TIPO CHECK (TIPO IN ('CARTÃO', 'DINHEIRO', 'PIX', 'BOLETO', 'DEPÓSITO'))
);

-- 6. Tabela PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    QTD_ESTOQUE INT DEFAULT 0 NOT NULL,
    PRECO_VENDA DECIMAL(10,2) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- 7. Tabela PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    DATA DATE NOT NULL,
    STATUS VARCHAR(12) NOT NULL,
    NFE CHAR(6),
    ID_CLIENTE INT NOT NULL,
    ID_PAGAMENTO INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    CONSTRAINT PEDIDO_CHK_STATUS check (STATUS IN ('NOVO', 'AGUARDANDO', 'FINALIZADO', 'CONCLUIDO')),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTO(ID_PAGAMENTO),
    CONSTRAINT FK_PEDIDO_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

-- 8. Tabela ORDEM_DE_SERVICO
CREATE TABLE ORDEM_DE_SERVICO (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(10) NOT NULL, 
    DIAGNOSTICO_TECNICO VARCHAR(200),
    APARELHO VARCHAR(150) NOT NULL,
    SERIAL_NUMBER VARCHAR(50) NOT NULL,
    DESCRICAO_PROBLEMA VARCHAR(200) NOT NULL,
    ENTRADA DATE NOT NULL,
    SAIDA DATE,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    ID_CLIENTE INT,
    ID_PAGAMENTO INT,
    CONSTRAINT SERVICO_CHK_STATUS CHECK (STATUS IN ('NOVO', 'AGUARDANDO', 'PENDENTE', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT FK_SERVICO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_SERVICO_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTO(ID_PAGAMENTO)
);


-- TABELAS DE ASSOCIAÇÃO (N:N)

-- 9. FORNECEDOR_PRODUTO
CREATE TABLE FORNECEDOR_PRODUTO (
    ID_FORNECEDOR INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    TEMPO_MEDIO_ENTREGA SMALLINT, -- DIAS
    VALOR_DE_COMPRA DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_FORNECEDOR, ID_PRODUTO),
    CONSTRAINT FK_FOR_PROD_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
    CONSTRAINT FK_FOR_PROD_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- 10. PRODUTO_PEDIDO (Itens do Pedido)
CREATE TABLE PRODUTO_PEDIDO (
    ID_PRODUTO INT  NOT NULL,
    ID_PEDIDO INT NOT NULL,
    QUANTIDADE INT NOT NULL  NOT NULL,
    VALOR_COMPRA DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_PRODUTO, ID_PEDIDO),
    CONSTRAINT FK_PROD_PED_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_PROD_PED_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

-- 11. SERVICO_PRODUTO (Peças usadas na manutenção)
CREATE TABLE SERVICO_PRODUTO (
    ID_SERVICO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_COMPRA DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_SERVICO, ID_PRODUTO),
    CONSTRAINT FK_SER_PROD_SERVICO FOREIGN KEY (ID_SERVICO) REFERENCES ORDEM_DE_SERVICO(ID_SERVICO),
    CONSTRAINT FK_SER_PROD_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- 12. CLIENTE_ENDERECO
CREATE TABLE CLIENTE_ENDERECO (
    ID_CLIENTE INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PRIMARY KEY (ID_CLIENTE, ID_ENDERECO),
    CONSTRAINT FK_CL_END_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_CL_END_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);